[package]

name = "fps"
version = "0.0.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

# [[bin]]
# name = "main"

[lib]
name = "fps"
crate-type = ["dylib"]

[dependencies.gunship]
version = "*"
path = "../gunship-rs"
