[package]

name = "fps"
version = "0.0.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[[bin]]
name = "main"

[lib]
name = "hotload"
crate-type = ["dylib"]

[dependencies.gunship]
version = "*"
path = "../gunship-rs"

[profile.release]
debug = true

[profile.dev]
opt-level = 3
debug = true
debug-assertions = true
codegen-units = 1
